// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "c615a12d-fe78-4585-9384-d4642bba5ab1";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFANChange();
void onLightChange();
void onMOTIONChange();

float temperature;
bool fAN;
bool light;
bool mOTION;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperature, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(fAN, READWRITE, 1 * SECONDS, onFANChange);
  ArduinoCloud.addProperty(light, READWRITE, 1 * SECONDS, onLightChange);
  ArduinoCloud.addProperty(mOTION, READWRITE, 1 * SECONDS, onMOTIONChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
